### PR TITLE
r #12967 make none_t constructor constexpr

### PR DESCRIPTION
**Pull request by citrusmoose**
https://svn.boost.org/trac/boost/ticket/12967

### CODE REVIEW

**Comment by MarcelRaad** [comment]
This will break compilers without constexpr support. You could use `BOOST_CONSTEXPR` from Boost.Config.

**Comment by citrusmoose** [comment]
Updated; thanks for pointing that out @MarcelRaad

**Comment by vlichevsky** [comment]
Hi! A friendly ping from boost::optional user. Are there any obstacles to merging this pull request? It would be very nice if it got some attention.

**Comment by akrzemi1** [comment]
Thank you for the reminder. It is now merged to develop.

**Pull request merged**
